name: grind
markdown: redcarpet
highlighter: pygments
baseurl: /grind

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

collections:
  tut:
    output: true
